### ISSUE TITLE
Experimental build

### ISSUE THREAD

**Issue by layton322** [cmxci/Create-1.19.2#1]
### Describe the Suggestion

Hi there, could you provide an experimental build for your 1.19.2 fork if possible? I tried to clone and build this myself but I am stuck on the gradle package dependencies (PortingLib, ForgeTags, Registrate and Flywheel). How did you get around these dependency issues? Thanks!

**Comment by Sheep7798** [comment]
You need to build the missing dependencies yourself

**Comment by cmxci** [comment]
I can try to have a build on here later today

**Comment by cmxci** [comment]
Release is done

**Comment by layton322** [comment]
Many thanks cmxci!
